move autovalue to annotation processor path
googleapis/java-storage-nio pull request #179
Opened 2020-07-27 15:14 UTC by elharo

@suraj-qlogic @suztomo

fixes #178

2020-07-27 15:30 UTC, elharo commented
2020-07-27T15:15:25.6293721Z [ERROR] com.google.cloud.storage.contrib.nio.CloudStorageFileAttributesTest.testAcl  Time elapsed: 0.451 s  <<< ERROR!
2020-07-27T15:15:25.6302204Z java.nio.file.FileSystemNotFoundException: Provider "gs" not installed
2020-07-27T15:15:25.6310326Z 	at com.google.cloud.storage.contrib.nio.CloudStorageFileAttributesTest.before(CloudStorageFileAttributesTest.java:49)
2020-07-27T15:15:25.6311534Z

2020-07-27 20:09 UTC, elharo commented
Just maybe relevant:

 [WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in Storage Parent:
[WARNING] org.codehaus.mojo:clirr-maven-plugin:2.8
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] ***

2020-07-27 20:24 UTC, elharo commented
tests are running in parallel and are not using random paths:

```
  @Before
  public void before() {
    CloudStorageFileSystemProvider.setStorageOptions(LocalStorageHelper.getOptions());
    path = Paths.get(URI.create("gs://bucket/randompath"));
    dir = Paths.get(URI.create("gs://bucket/randompath/"));
  }
```

2021-01-26 21:18 UTC, frankyn commented
This issue might be related to recent failures. Not quite sure what's going on though as I'm not able to repro this issue locally.

2021-01-26 23:45 UTC, frankyn commented
Woot, looks like things are passing now. Pending review from @BenWhitehead when he's back in the office tomorrow.

2021-01-27 13:18 UTC, elharo commented on google-cloud-nio/pom.xml
> +              <version>1.7.3</version>
1.7.4 is out now

2021-01-27 14:57 UTC, elharo commented
```
com.google.api.client.http.HttpResponseException:
403 Forbidden

POST https://storage.googleapis.com:443/upload/storage/v1/b/bucket/o?uploadType=resumable&name=randompath
{
  "error": {
    "code": 403,
    "message": "it-service-account@gcloud-devel.iam.gserviceaccount.com does not have storage.objects.create access to bucket/randompath.",
    "errors": [
      {
        "message": "it-service-account@gcloud-devel.iam.gserviceaccount.com does not have storage.objects.create access to bucket/randompath.",
        "domain": "global",
        "reason": "forbidden"
      }
    ]
  }
```

2021-01-27 19:03 UTC, frankyn commented
Will continue debugging. This looks related to the open failures that exist right now.

2021-01-27 20:57 UTC, frankyn approved these changes

2021-01-27 20:58 UTC, frankyn commented
@elharo I found that auto-processor was missing in plugins which helped generate the META-INF/ file that's expected.

If it looks good to you, can we merge this in?

2021-01-27 20:58 UTC, BenWhitehead requested changes
Shared config has had auto-value support for some time.

We should be able to remove auto-value and auto-service and use the config from shared config.

See https://github.com/googleapis/java-firestore/pull/221/files for an example of it being used in Firestore.

2021-01-28 15:04 UTC, elharo reviewed
@BenWhitehead PTAL. The commit history is becoming convoluted, but I think this is now what you asked for,

2021-01-28 18:18 UTC, frankyn commented
Stuck on:
```
[INFO] <<< maven-dependency-plugin:3.1.2:analyze (default-cli) < test-compile @ google-cloud-nio <<<
[INFO] 
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.2:analyze (default-cli) @ google-cloud-nio ---
Warning:  Used undeclared dependencies found:
Warning:     com.google.auto.value:auto-value-annotations:jar:1.7.4:compile
```

Thanks @elharo!

2021-01-28 21:29 UTC, frankyn commented
Kokoro integrations failed again. I think it might be a flake and not sure how to reinforce without doing a retry of the tests.

2021-01-28 22:16 UTC, frankyn commented
Chatting with @BenWhitehead, the kokoro build change to retry tests will be removed by autosynth...

2021-01-28 22:23 UTC, BenWhitehead approved these changes

2021-01-28 22:26 UTC, frankyn commented
We will merge this PR once jobs pass and will follow-up with another solution provided by @BenWhitehead for flaky integration tests to separate tasks. 
I'm still on the hook as part of On Duty.

2021-01-28 22:30 UTC, merged